// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjramiHdEFkW9yX1dURHppPgqXi4YSwo4',
    appId: '1:713246683474:web:5f6662d92ffbe7654a8a8b',
    messagingSenderId: '713246683474',
    projectId: 'dlr-zone',
    authDomain: 'dlr-zone.firebaseapp.com',
    storageBucket: 'dlr-zone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9bbz7xeQpRGFq_-zBqrkMkBidjW9U2Q',
    appId: '1:713246683474:android:dd79f24fd45d4a914a8a8b',
    messagingSenderId: '713246683474',
    projectId: 'dlr-zone',
    storageBucket: 'dlr-zone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPaCHVkqYk1LWtml_-y9RyDdREJGKrMTk',
    appId: '1:713246683474:ios:52e9c7a7bf0fd25d4a8a8b',
    messagingSenderId: '713246683474',
    projectId: 'dlr-zone',
    storageBucket: 'dlr-zone.firebasestorage.app',
    iosBundleId: 'com.example.mobileAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPaCHVkqYk1LWtml_-y9RyDdREJGKrMTk',
    appId: '1:713246683474:ios:52e9c7a7bf0fd25d4a8a8b',
    messagingSenderId: '713246683474',
    projectId: 'dlr-zone',
    storageBucket: 'dlr-zone.firebasestorage.app',
    iosBundleId: 'com.example.mobileAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjramiHdEFkW9yX1dURHppPgqXi4YSwo4',
    appId: '1:713246683474:web:729e6f30c908c5e04a8a8b',
    messagingSenderId: '713246683474',
    projectId: 'dlr-zone',
    authDomain: 'dlr-zone.firebaseapp.com',
    storageBucket: 'dlr-zone.firebasestorage.app',
  );

}