name: firebase_auth_impl
description: Firebase-backed implementation of core_contracts AuthRepository.
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  core_contracts:
    path: ../core_contracts
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.3.0
